services:
  # FastAPI Backend
  - type: web
    name: nexus-backend
    env: docker
    rootDir: backend
    plan: free
    region: singapore
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: PORT
        value: 8080
